# Generated by Django 3.2.9 on 2022-09-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_phone', models.IntegerField()),
                ('sel_phone', models.ImageField(upload_to='')),
                ('location', models.TextField()),
                ('facebook', models.TextField()),
                ('twitter', models.TextField()),
                ('linkdean', models.TextField()),
                ('logo_footer', models.ImageField(upload_to=None)),
                ('logo_header', models.ImageField(upload_to=None)),
                ('footer_description', models.TextField()),
            ],
            options={
                'verbose_name': 'offive_Phone',
                'verbose_name_plural': 'Office Phone',
            },
        ),
    ]
