# Generated by Django 3.2.9 on 2022-09-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highkel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hader',
            name='logo_footer',
            field=models.ImageField(upload_to='Header'),
        ),
        migrations.AlterField(
            model_name='hader',
            name='office_phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hader',
            name='sel_phone',
            field=models.TextField(),
        ),
    ]
