# Generated by Django 3.2.9 on 2022-09-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highkel_app', '0002_auto_20220924_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hader',
            name='logo_header',
            field=models.ImageField(upload_to='Header'),
        ),
    ]
