# Generated by Django 3.2.9 on 2022-09-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highkel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('slogone', models.TextField()),
                ('logo_footer', models.ImageField(upload_to='slide')),
                ('list_title', models.TextField(max_length=100)),
                ('lift_discription', models.TextField(max_length=100)),
                ('right_title', models.TextField(max_length=100)),
                ('ritht_discription', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'slogone',
                'verbose_name_plural': 'Slider',
            },
        ),
        migrations.AlterField(
            model_name='hader',
            name='facebook',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hader',
            name='footer_description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='hader',
            name='linkdean',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hader',
            name='location',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hader',
            name='office_phone',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hader',
            name='sel_phone',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hader',
            name='twitter',
            field=models.TextField(max_length=100),
        ),
    ]
