# Generated by Django 3.2.9 on 2022-09-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highkel_app', '0002_auto_20220925_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hader',
            options={'verbose_name': 'offive_Phone', 'verbose_name_plural': 'Header'},
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='logo_footer',
            new_name='image',
        ),
    ]
