# Generated by Django 3.2.9 on 2022-09-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highkel_app', '0003_auto_20220925_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='discriptions',
            field=models.TextField(default='highkel'),
        ),
    ]
