# Generated by Django 3.2.9 on 2022-09-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highkel_app', '0004_slider_discriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highkel_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_completed', models.TextField(max_length=100)),
                ('project_completed_icon', models.ImageField(upload_to='slide')),
                ('patients_satisfied', models.TextField(max_length=100)),
                ('patients_satisfied_icon', models.ImageField(upload_to='slide')),
                ('medical_beds', models.TextField(max_length=100)),
                ('medical_beds_icon', models.ImageField(upload_to='slide')),
                ('Laboratory_experts', models.TextField(max_length=100)),
                ('Laboratory_experts_icon', models.ImageField(upload_to='slide')),
                ('service1', models.TextField(max_length=100)),
                ('service1_discription', models.TextField(max_length=100)),
                ('service2', models.TextField(max_length=100)),
                ('service2_discription', models.TextField(max_length=100)),
                ('service3', models.TextField(max_length=100)),
                ('service3_discription', models.TextField(max_length=100)),
                ('service1_icon', models.ImageField(upload_to='slide')),
                ('service2_icon', models.ImageField(upload_to='slide')),
                ('service3_icon', models.ImageField(upload_to='slide')),
                ('back_icon', models.ImageField(upload_to='slide')),
            ],
            options={
                'verbose_name': 'Highkel_status',
                'verbose_name_plural': 'Highkel Status',
            },
        ),
    ]
