# Generated by Django 3.2.9 on 2022-09-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highkel_app', '0005_highkel_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Highkel_status',
            new_name='status',
        ),
    ]
