# Generated by Django 3.2.9 on 2022-09-29 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('highkel_app', '0006_rename_highkel_status_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'project_completed', 'verbose_name_plural': 'Highkel Status'},
        ),
    ]
